version: '3'
services:
  app:
    image: golang:1.11.1
    volumes:
      - ./:/api/blog-api/
    working_dir: /api/blog-api/
    environment:
      - GO111MODULE=on 
      - CGO_ENABLED=0
    command: |
      bash -c " \
      echo '=== Setup ===' && \
      go get -u github.com/oxequa/realize && \
      realize start"
    ports:
      - 8080:8080
      - 6666:6060
